version: '2.1'

services:
  nextcloud-app:
    image: nextcloud:fpm
    restart: always
    mem_limit: 1g
    depends_on:
      - nextcloud-database
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=cloud
      - MYSQL_USER=cloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - TZ=${TZ}
    tmpfs:
      - /tmp
    volumes:
      #- nextcloud-www-vol-1:/var/www/html
      - ./data/app:/var/www/html
    networks:
      nextcloud-network:
        ipv4_address: 172.22.5.100
        aliases:
          - app

  nextcloud-web:
    build: ./web
    restart: always
    ports:
      - "${NEXTCLOUD_WEB_BIND:-127.0.0.1}:${NEXTCLOUD_WEB_PORT:-8080}:80"
    volumes:
      #- nextcloud-www-vol-1:/var/www/html:ro
      - ./data/app:/var/www/html:ro
    depends_on:
      - nextcloud-app
    networks:
      nextcloud-network:
        ipv4_address: 172.22.5.101
        aliases:
          - web

  nextcloud-database:
    image: mariadb:10.2
    restart: always
    mem_limit: 2g
    command: mysqld --skip-name-resolve --skip-host-cache --log-warnings=0
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DATABASE_ROOT}
      - MYSQL_DATABASE=cloud
      - MYSQL_USER=cloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}
    volumes:
      -  nextcloud-db-vol-1:/var/lib/mysql/
      - ./data/conf/mysql:/etc/mysql/conf.d/:ro
    tmpfs:
      - /tmp
    networks:
      nextcloud-network:
        ipv4_address: 172.22.5.102
        aliases:
          - mysql

networks:
  nextcloud-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.22.5.0/24

volumes:
  nextcloud-db-vol-1:
  #nextcloud-www-vol-1:
